#pragma once
void testDomain();
void testRepositoryArray();
void testRepositorySTL();
void testService();
void testRepoArrayFindProjectsWithAtLeastKBranchesAndLCommits();
void testRepoArrayDeleteProjectsWithZeroBranchesOrCommits();
void testRepoSTLFindProjectsWithAtLeastKBranchesAndLCommits();
void testRepoSTLDeleteProjectsWithZeroBranchesOrCommits();